version: '3.8'

services:
  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: givebase_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    networks:
      - givebase_network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: givebase_frontend
    command: npm run dev -- --hostname 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_DJANGO_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - givebase_network
    restart: unless-stopped

networks:
  givebase_network:
    driver: bridge