# Generated by Django 4.2.7 on 2025-10-16 09:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recipient_address', models.CharField(max_length=42)),
                ('goal_amount', models.DecimalField(decimal_places=18, default=Decimal('1.0'), max_digits=20)),
                ('raised_amount', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=20)),
                ('category', models.CharField(choices=[('humanitarian', 'Humanitarian Aid'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('environment', 'Environment'), ('disaster', 'Disaster Relief'), ('community', 'Community')], default='humanitarian', max_length=20)),
                ('emoji', models.CharField(default='💝', max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('total_donated', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=20)),
                ('donation_count', models.IntegerField(default=0)),
                ('sub_account_address', models.CharField(blank=True, max_length=42, null=True)),
                ('has_sub_account', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_donated'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_address', models.CharField(db_index=True, max_length=42)),
                ('sub_account_address', models.CharField(blank=True, max_length=42, null=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=20)),
                ('tx_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('used_spend_permission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_donati_created_ed4d90_idx'), models.Index(fields=['donor_address', '-created_at'], name='core_donati_donor_a_a39eb3_idx')],
            },
        ),
    ]
