# Generated by Django 4.2.7 on 2025-10-17 03:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('100.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='raised_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_donated',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
    ]
